[package]
name = "tiny_chat"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.20"
futures = "0.3"
colored = "2.0"

[[bin]]
name = "server"
path = "src/main.rs"
